version: '3.8'

services:
  vllm-server-qwen3-next-80b-thinking:
    image: vllm/vllm-openai:nightly # Use nightly image for Qwen3-Next models
    shm_size: 100g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1', '2', '3', '4', '5', '6', '7']  # Use all 8 GPUs for 80B model
              capabilities: [gpu]
    volumes:
      - /mnt/disk3/Qwen_Qwen3-Next-80B-A3B-Thinking:/models
    ports:
      - "8801:8000"  # Map internal port 8000 to external 8801
    environment:
      - NCCL_IGNORE_DISABLED_P2P=1
      - VLLM_ATTENTION_BACKEND=TRITON_ATTN_VLLM_V1
      - VLLM_USE_MODELSCOPE=true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8000/v1/models" ]
      interval: 30s
      timeout: 5s
      retries: 20
    command:
      - --model=/models
      - --tensor-parallel-size=8
      - --served-model-name=qwen3-next-80b-thinking
      - --trust-remote-code
      - --max-model-len=24576
      - --dtype=auto
      - --gpu-memory-utilization=0.92
      - --max-num-seqs=128
      - --max-num-batched-tokens=32768
      - --enable-chunked-prefill
      - --enforce-eager
    restart: unless-stopped