analysis_report: false
api_url: http://localhost:8801/v1/chat/completions
chat_template: null
dataset_args:
  code_switching:
    aggregation: mean
    dataset_id: airesearch/WangchanThaiInstruct
    default_subset: default
    description: Thai-English code switching evaluation benchmark using WangchanThaiInstruct
      dataset. Tests the model's ability to understand and generate mixed Thai-English
      text, with responses expected to be primarily in Thai.
    eval_split: train
    extra_params:
      dataset_hub: huggingface
    few_shot_num: 0
    few_shot_prompt_template: null
    few_shot_random: false
    filters: null
    metric_list:
    - accuracy: {}
    name: code_switching
    output_types:
    - generation
    pretty_name: Code-Switching-Thai-English
    prompt_template: '{question}'
    query_template: null
    shuffle: false
    shuffle_choices: false
    subset_list:
    - default
    system_prompt: null
    tags:
    - QA
    train_split: train
dataset_dir: /home/saiuser/.cache/modelscope/hub/datasets
dataset_hub: huggingface
datasets:
- code_switching
debug: false
eval_backend: Native
eval_batch_size: 1
eval_config: null
eval_type: openai_api
generation_config:
  batch_size: 1
  do_sample: false
  max_new_tokens: 16384
  temperature: 0.0
  timeout: 300.0
ignore_errors: false
judge_model_args: {}
judge_strategy: auto
judge_worker_num: 1
limit: 10
model: gpt-oss-20b
model_args: {}
model_id: gpt-oss-20b
model_task: text_generation
repeats: 1
rerun_review: false
seed: 42
stream: null
timeout: 300.0
use_cache: null
work_dir: test_output_api_code_switching/20250916_073121
