analysis_report: false
api_url: http://localhost:8801/v1/chat/completions
chat_template: null
dataset_args:
  live_code_bench:
    aggregation: mean
    dataset_id: livecodebench/code_generation_lite
    default_subset: default
    description: Live Code Bench is a benchmark for evaluating code generation models
      on real-world coding tasks. It includes a variety of programming problems with
      test cases to assess the model's ability to generate correct and efficient code
      solutions.
    eval_split: test
    extra_params:
      debug: false
      end_date: null
      start_date: null
      timeout: 6
    few_shot_num: 0
    few_shot_prompt_template: null
    few_shot_random: false
    filters: null
    metric_list:
    - Pass@1
    name: live_code_bench
    output_types:
    - generation
    pretty_name: Live-Code-Bench
    prompt_template: '### Question:

      {question_content}


      {format_prompt} ### Answer: (use the provided format with backticks)


      '
    query_template: null
    shuffle: false
    shuffle_choices: false
    subset_list:
    - release_latest
    system_prompt: null
    tags:
    - Coding
    train_split: null
dataset_dir: /home/saiuser/.cache/modelscope/hub/datasets
dataset_hub: huggingface
datasets:
- live_code_bench
debug: false
eval_backend: Native
eval_batch_size: 1
eval_config: null
eval_type: openai_api
generation_config:
  batch_size: 1
  do_sample: false
  max_new_tokens: 16384
  temperature: 0.0
  timeout: 300.0
ignore_errors: false
judge_model_args: {}
judge_strategy: auto
judge_worker_num: 1
limit: 1
model: gpt-oss-20b
model_args: {}
model_id: gpt-oss-20b
model_task: text_generation
repeats: 1
rerun_review: false
seed: 42
stream: null
timeout: 300.0
use_cache: null
work_dir: thai_benchmark_results_api/live_code_bench/20250916_091517
