analysis_report: false
api_url: http://localhost:8801/v1/chat/completions
chat_template: null
dataset_args:
  math_500:
    aggregation: mean
    dataset_id: AI-ModelScope/MATH-500
    default_subset: default
    description: MATH-500 is a benchmark for evaluating mathematical reasoning capabilities
      of AI models. It consists of 500 diverse math problems across five levels of
      difficulty, designed to test a model's ability to solve complex mathematical
      problems by generating step-by-step solutions and providing the correct final
      answer.
    eval_split: test
    extra_params: {}
    few_shot_num: 0
    few_shot_prompt_template: null
    few_shot_random: false
    filters: null
    metric_list:
    - acc:
        numeric: true
    name: math_500
    output_types:
    - generation
    pretty_name: MATH-500
    prompt_template: '{question}

      Please reason step by step, and put your final answer within \boxed{{}}.'
    query_template: null
    shuffle: false
    shuffle_choices: false
    subset_list:
    - Level 1
    - Level 2
    - Level 3
    - Level 4
    - Level 5
    system_prompt: null
    tags:
    - Math
    - Reasoning
    train_split: null
dataset_dir: /home/saiuser/.cache/modelscope/hub/datasets
dataset_hub: huggingface
datasets:
- math_500
debug: false
eval_backend: Native
eval_batch_size: 1
eval_config: null
eval_type: openai_api
generation_config:
  batch_size: 1
  do_sample: false
  max_new_tokens: 32768
  temperature: 0.0
  timeout: 300.0
ignore_errors: false
judge_model_args: {}
judge_strategy: auto
judge_worker_num: 1
limit: 500
model: gpt-oss-120b
model_args: {}
model_id: gpt-oss-120b
model_task: text_generation
repeats: 1
rerun_review: false
seed: 42
stream: null
timeout: 300.0
use_cache: null
work_dir: thai_benchmark_results_api/gpt-oss-120b/math_500/20250918_135209
