analysis_report: false
api_url: http://localhost:8801/v1/chat/completions
chat_template: null
dataset_args:
  ifeval-th:
    aggregation: mean
    dataset_id: scb10x/ifeval-th
    default_subset: default
    description: IFEval Thai is a benchmark for evaluating instruction-following language
      models in Thai language, focusing on their ability to understand and respond
      to various prompts.
    eval_split: train
    extra_params:
      dataset_hub: huggingface
    few_shot_num: 0
    few_shot_prompt_template: null
    few_shot_random: false
    filters: null
    metric_list:
    - prompt_level_strict
    - inst_level_strict
    - prompt_level_loose
    - inst_level_loose
    name: ifeval-th
    output_types:
    - generation
    pretty_name: IFEval-Thai
    prompt_template: 'คุณคือผู้ช่วยอัจฉริยะที่ต้องปฏิบัติตามคำสั่งอย่างระมัดระวังและแม่นยำ


      {question}'
    query_template: null
    shuffle: false
    shuffle_choices: false
    subset_list:
    - default
    system_prompt: null
    tags:
    - InstructionFollowing
    train_split: null
dataset_dir: /home/saiuser/.cache/modelscope/hub/datasets
dataset_hub: modelscope
datasets:
- ifeval-th
debug: false
eval_backend: Native
eval_batch_size: 1
eval_config: null
eval_type: openai_api
generation_config:
  batch_size: 1
  do_sample: false
  max_new_tokens: 16384
  temperature: 0.0
  timeout: 300.0
ignore_errors: false
judge_model_args: {}
judge_strategy: auto
judge_worker_num: 1
limit: 1
model: gpt-oss-20b
model_args: {}
model_id: gpt-oss-20b
model_task: text_generation
repeats: 1
rerun_review: false
seed: 42
stream: null
timeout: 300.0
use_cache: null
work_dir: thai_benchmark_results_api/ifeval-th/20250916_042102
