analysis_report: false
api_url: http://localhost:8801/v1/chat/completions
chat_template: null
dataset_args:
  humaneval:
    aggregation: mean
    dataset_id: opencompass/humaneval
    default_subset: default
    description: HumanEval is a benchmark for evaluating the ability of code generation
      models to write Python functions based on given specifications. It consists
      of programming tasks with a defined input-output behavior.
    eval_split: test
    extra_params:
      num_workers: 4
      timeout: 4
    few_shot_num: 0
    few_shot_prompt_template: null
    few_shot_random: false
    filters: null
    metric_list:
    - Pass@1
    name: humaneval
    output_types:
    - generation
    pretty_name: HumanEval
    prompt_template: 'Read the following function signature and docstring, and fully
      implement the function described. Your response should only contain the code
      for this function.

      {question}'
    query_template: null
    shuffle: false
    shuffle_choices: false
    subset_list:
    - openai_humaneval
    system_prompt: null
    tags:
    - Coding
    train_split: null
dataset_dir: /home/saiuser/.cache/modelscope/hub/datasets
dataset_hub: huggingface
datasets:
- humaneval
debug: false
eval_backend: Native
eval_batch_size: 1
eval_config: null
eval_type: openai_api
generation_config:
  batch_size: 1
  do_sample: false
  max_new_tokens: 16384
  temperature: 0.0
  timeout: 300.0
ignore_errors: false
judge_model_args: {}
judge_strategy: auto
judge_worker_num: 1
limit: 1
model: gpt-oss-20b
model_args: {}
model_id: gpt-oss-20b
model_task: text_generation
repeats: 1
rerun_review: false
seed: 42
stream: null
timeout: 300.0
use_cache: null
work_dir: thai_benchmark_results_api/humaneval/20250916_040422
