analysis_report: false
api_url: http://localhost:8801/v1/chat/completions
chat_template: null
dataset_args:
  openthaieval:
    aggregation: mean
    dataset_id: iapp/openthaieval
    default_subset: default
    description: Thai national examination questions (O-NET, TGAT, A-Level, etc.)
      testing general knowledge and reasoning in Thai language. Contains 1,232 questions
      across 17 exam types.
    eval_split: test
    extra_params:
      dataset_hub: huggingface
      trust_remote_code: true
    few_shot_num: 0
    few_shot_prompt_template: null
    few_shot_random: false
    filters: null
    metric_list:
    - accuracy: {}
    name: openthaieval
    output_types:
    - generation
    pretty_name: OpenThaiEval
    prompt_template: '{question}'
    query_template: null
    shuffle: false
    shuffle_choices: false
    subset_list:
    - all
    system_prompt: null
    tags:
    - MCQ
    - Reasoning
    train_split: null
dataset_dir: /home/saiuser/.cache/modelscope/hub/datasets
dataset_hub: huggingface
datasets:
- openthaieval
debug: false
eval_backend: Native
eval_batch_size: 1
eval_config: null
eval_type: openai_api
generation_config:
  batch_size: 1
  do_sample: false
  max_new_tokens: 16384
  temperature: 0.0
  timeout: 300.0
ignore_errors: false
judge_model_args: {}
judge_strategy: auto
judge_worker_num: 1
limit: 10
model: gpt-oss-20b
model_args: {}
model_id: gpt-oss-20b
model_task: text_generation
repeats: 1
rerun_review: false
seed: 42
stream: null
timeout: 300.0
use_cache: null
work_dir: test_output_api_openthaieval/20250916_075632
